import React from 'react';
import Avatar from '@mui/material/Avatar';

export const columns = [
    { field: 'title', headerName: 'Title', width: 200 },
    { field: 'appId', headerName: 'App ID', width: 150 },
    { field: 'url', headerName: 'Icon', width: 100, renderCell: (params) => <Avatar src={params.value} alt="Icon" /> },
    { field: 'developer', headerName: 'Developer', width: 150 },
    { field: 'currency', headerName: 'Currency', width: 70 },
    { field: 'price', headerName: 'Price', width: 50 },
    { field: 'free', headerName: 'Free', width: 50 },
    { field: 'summary', headerName: 'Summary', width: 200 },
    { field: 'scoreText', headerName: 'Score Text', width: 100 },
    { field: 'score', headerName: 'Score', width: 100 },
    { field: 'source', headerName: 'Source', width: 100 },
    { field: 'installs', headerName: 'Installs', width: 100 },
    { field: 'maxInstalls', headerName: 'Max Installs', width: 100 },
    { field: 'ratings', headerName: 'Ratings', width: 100 },
    { field: 'originalPrice', headerName: 'Original Price', width: 100 },
    { field: 'discountEndDate', headerName: 'Discount End Date', width: 150 },
    { field: 'available', headerName: 'Available', width: 70 },
    { field: 'offersIAP', headerName: 'Offers IAP', width: 80 },
    { field: 'IAPRange', headerName: 'IAP Range', width: 200 },
    { field: 'androidVersion', headerName: 'Android Version', width: 120 },
    { field: 'androidMaxVersion', headerName: 'Android Max Version', width: 150 },
    { field: 'developerId', headerName: 'Developer Id', width: 200 },
    { field: 'developerEmail', headerName: 'Developer Email', width: 200 },
    { field: 'developerWebsite', headerName: 'Developer Website', width: 200 },
    { field: 'developerAddress', headerName: 'Developer Address', width: 200 },
    { field: 'privacyPolicy', headerName: 'Privacy Policy', width: 200 },
    { field: 'genre', headerName: 'Genre', width: 150 },
    { field: 'genreId', headerName: 'Genre Id', width: 200 },
    { field: 'previewVideo', headerName: 'Preview Video', width: 200 },
    { field: 'contentRating', headerName: 'Content Rating', width: 120 },
    { field: 'adSupported', headerName: 'Ad Supported', width: 100 },
    { field: 'released', headerName: 'Released', width: 100 },
    { field: 'version', headerName: 'Version', width: 100 },
    { field: 'recentChanges', headerName: 'Recent Changes', width: 200 }
  ];