import React from 'react';
import Avatar from '@mui/material/Avatar';
import CheckIcon from '@mui/icons-material/Check';
import CloseIcon from '@mui/icons-material/Close';
import { Tooltip } from '@mui/material';

export const permissionColumns = [
    { field: 'title', renderHeader: () => <strong>Title</strong>, width: 200 },
    { field: 'appId', renderHeader: () => <strong>App ID</strong>, width: 150 },
    { field: 'icon', renderHeader: () => <strong>Icon</strong>, width: 100, renderCell: (params) => <Avatar src={params.value} alt="Icon" /> },
    { field: 'developer', renderHeader: () => <strong>Developer</strong>, width: 150 },
    { field: 'currency', renderHeader: () => <strong>Currency</strong>, width: 100 },
    { field: 'price', renderHeader: () => <strong>Price</strong>, width: 50 },
    { field: 'free', renderHeader: () => <strong>Free</strong>, width: 50 },
    { field: 'summary', renderHeader: () => <strong>Summary</strong>, width: 200 },
    { field: 'url', renderHeader: () => <strong>URL</strong>, width: 200 },
    { field: 'scoreText', renderHeader: () => <strong>Score Text</strong>, width: 100 },
    { field: 'score', renderHeader: () => <strong>Score</strong>, width: 100 },
    { field: 'source', renderHeader: () => <strong>Source</strong>, width: 100 },
    { field: 'installs', renderHeader: () => <strong>Installs</strong>, width: 100 },
    { field: 'maxInstalls', renderHeader: () => <strong>Max Installs</strong>, width: 100 },
    { field: 'ratings', renderHeader: () => <strong>Ratings</strong>, width: 100 },
    { field: 'originalPrice', renderHeader: () => <strong>Original Price</strong>, width: 100, renderCell: (params) => params.value ? params.value : "-"},
    { field: 'discountEndDate', renderHeader: () => <strong>Discount End Date</strong>, width: 150, renderCell: (params) => params.value ? params.value : "-"},
    { field: 'available', renderHeader: () => <strong>Available</strong>, width: 70 },
    { field: 'offersIAP', renderHeader: () => <strong>Offers IAP</strong>, width: 80 },
    { field: 'IAPRange', renderHeader: () => <strong>IAP Range</strong>, width: 200 },
    { field: 'androidVersion', renderHeader: () => <strong>Android Version</strong>, width: 120 },
    { field: 'androidMaxVersion', renderHeader: () => <strong>Android Max Version</strong>, width: 150 },
    { field: 'developerId', renderHeader: () => <strong>Developer Id</strong>, width: 200 },
    { field: 'developerEmail', renderHeader: () => <strong>Developer Email</strong>, width: 200 },
    { field: 'developerWebsite', renderHeader: () => <strong>Developer Website</strong>, width: 200 },
    { field: 'developerAddress', renderHeader: () => <strong>Developer Address</strong>, width: 200 },
    { field: 'privacyPolicy', renderHeader: () => <strong>Privacy Policy</strong>, width: 200 },
    { field: 'genre', renderHeader: () => <strong>Genre</strong>, width: 150 },
    { field: 'genreId', renderHeader: () => <strong>Genre Id</strong>, width: 200 },
    { field: 'previewVideo', renderHeader: () => <strong>Preview Video</strong>, width: 100, renderCell: (params) => params.value ? params.value : "-"},
    { field: 'contentRating', renderHeader: () => <strong>Content Rating</strong>, width: 120 },
    { field: 'adSupported', renderHeader: () => <strong>Ad Supported</strong>, width: 100 },
    { field: 'released', renderHeader: () => <strong>Released</strong>, width: 100 },
    { field: 'version', renderHeader: () => <strong>Version</strong>, width: 100 },
    { field: 'recentChanges', renderHeader: () => <strong>Recent Changes</strong>, width: 200 },

    { field: 'approximateLocation', renderHeader: () =>  <Tooltip title ="approximate location (network based)"><p class="permissions-headers"><strong>Approximate location (network based)</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'preciseLocation', renderHeader: () => <Tooltip title = "precise location (GPS and network-based)"><p class="permissions-headers"><strong>Precise location (GPS and network-based)</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'retrieveRunning', renderHeader: () => <Tooltip title = "retrieve running apps"><p class="permissions-headers"><strong>Retrieve running apps</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'findAccounts', renderHeader: () => <Tooltip title = "find accounts on the device"><p class="permissions-headers"><strong>Find accounts on the device</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'addRemoveAccounts', renderHeader: () => <Tooltip title = "add or remove accounts"><p class="permissions-headers"><strong>Add or Remove Accounts</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'readContact', renderHeader: () => <Tooltip title = "read your own contact card" ><p class="permissions-headers"><strong>Read your own Contact Card</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'readCalendar', renderHeader: () => <Tooltip title = 'read calendar events plus confidential information' ><p class="permissions-headers"><strong>Read calendar events plus confidential information</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'addModCalendar', renderHeader: () => <Tooltip title = 'add or modify calendar events and send email to guests without owners knowledge'><p class="permissions-headers"><strong> Add or modify calendar events and send email to guests without owners knowledge</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'readContacts', renderHeader: () => <Tooltip title = "read your contacts" ><p class="permissions-headers"><strong>Read Your Contacts</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'modifyContacts', renderHeader: () => <Tooltip title = 'modify your contacts' ><p class="permissions-headers"><strong>Modify Your Contacts</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'readCallLog', renderHeader: () => <Tooltip title = 'read call log' ><p class="permissions-headers"><strong>Read call log</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'directCall', renderHeader: () => <Tooltip title = 'directly call phone numbers' ><p class="permissions-headers"><strong>Directly call phone numbers</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'readPhoneStatus', renderHeader: () => <Tooltip title = 'Read phone status and identity' ><p class="permissions-headers"><strong>Read phone status and identity</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'readUSB', renderHeader: () => <Tooltip title = 'Read the contents of your USB storage' ><p class="permissions-headers"><strong>Read the contents of your USB storage</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'modUSB', renderHeader: () => <Tooltip title = 'modify or delete the contents of your USB storage' ><p class="permissions-headers"><strong>Modify or delete the contents of your USB storage</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'takePics', renderHeader: () => <Tooltip title = 'take pictures and videos' ><p class="permissions-headers"><strong>Take pictures and videos</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'recordAudio', renderHeader: () => <Tooltip title = 'Record audio' ><p class="permissions-headers"><strong>Record Audio</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'viewWifi', renderHeader: () => <Tooltip title = 'view Wi-Fi connections' ><p class="permissions-headers"><strong>View Wi-Fi connections</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'viewNetwork', renderHeader: () => <Tooltip title = 'view network connections' ><p class="permissions-headers"><strong>View network connections</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'createAccounts', renderHeader: () => <Tooltip title = 'create accounts and set passwords' ><p class="permissions-headers"><strong>Create accounts and set passwords</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'readBattery', renderHeader: () => <Tooltip title = 'read battery statistics' ><p class="permissions-headers"><strong>Read battery statistics</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'pairBluetooth', renderHeader: () => <Tooltip title = 'pair with Bluetooth devices' ><p class="permissions-headers"><strong>Pair with Bluetooth devices</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'accessBluetooth', renderHeader: () => <Tooltip title = 'access Bluetooth settings' ><p class="permissions-headers"><strong>Access Bluetooth settings</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'sendStickyBroadcast', renderHeader: () => <Tooltip title = 'send sticky broadcast' ><p class="permissions-headers"><strong>Send sticky broadcast</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'changeNetwork', renderHeader: () => <Tooltip title = 'change network connectivity' ><p class="permissions-headers"><strong>Change network connectivity</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'connectWifi', renderHeader: () => <Tooltip title = 'connect and disconnect from Wi-Fi' ><p class="permissions-headers"><strong>Connect and disconnect from Wi-Fi</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'fullNetworkAccess', renderHeader: () => <Tooltip title = 'full network access' ><p class="permissions-headers"><strong>Full network access</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'changeAudio', renderHeader: () => <Tooltip title = 'change your audio settings' ><p class="permissions-headers"><strong>Change your audio settings</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'controlNFC', renderHeader: () => <Tooltip title = 'control Near Field Communication' ><p class="permissions-headers"><strong>Control Near Field Communication</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'readSync', renderHeader: () => <Tooltip title = 'read sync settings' ><p class="permissions-headers"><strong>Read sync settings</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'runAtStart', renderHeader: () => <Tooltip title = 'run at startup'><p class="permissions-headers"><strong>Run at startup</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'reorderRunnning', renderHeader: () => <Tooltip title = 'reorder running apps'><p class="permissions-headers"><strong>Reorder running apps</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'drawOver', renderHeader: () => <Tooltip title = 'draw over other apps'><p class="permissions-headers"><strong>Draw over other apps</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'controlVibration', renderHeader: () => <Tooltip title = 'control vibration'><p class="permissions-headers"><strong>Control vibration</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'preventSleep', renderHeader: () => <Tooltip title = 'prevent device from sleeping'><p class="permissions-headers"><strong>Prevent device from sleeping</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'toggleSync', renderHeader: () => <Tooltip title = 'toggle sync on and off'><p class="permissions-headers"><strong>Toggle sync on and off</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'installShortcuts', renderHeader: () => <Tooltip title = 'install shortcuts'><p class="permissions-headers"><strong>Install shortcuts</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},
    { field: 'readGoogleConfig', renderHeader: () => <Tooltip title = 'read Google service configuration'><p class="permissions-headers"><strong>Read Google service configuration</strong></p></Tooltip>,width: 200, renderCell: (params) => params.value ? <CheckIcon color="success"/> : <CloseIcon color="error"/>},

];