import React from "react";


export const gplayCollections = [
    {code: "TOP_FREE", name: "Top Free"},
    {code: "TOP_PAID", name: "Top Paid"},
    {code: "GROSSING", name: "Top Grossing"},
]

export const gplayCategories = [
    {code: "", name: "Category (Optional)"},
    {code: "APPLICATION", name: "Application"},
    {code: "ANDROID_WEAR", name: "Android Wear"},
    {code: "ART_AND_DESIGN", name: "Art and Design"},
    {code: "AUTO_AND_VEHICLES", name: "Auto and Vehicle"},
    {code: "BEAUTY", name: "Beauty"},
    {code: "BOOKS_AND_REFERENCE", name: "Books and Reference"},
    {code: "BUSINESS", name: "Business"},
    {code: "COMICS", name: "Comics"},
    {code: "COMMUNICATION", name: "Communication"},
    {code: "DATING", name: "Dating"},
    {code: "EDUCATION", name: "Education"},
    {code: "ENTERTAINMENT", name: "Entertainment"},
    {code: "EVENTS", name: "Events"},
    {code: "FINANCE", name: "Finance"},
    {code: "FOOD_AND_DRINK", name: "Food and Drink"},
    {code: "HEALTH_AND_FITNESS", name: "Health and Fitness"},
    {code: "HOUSE_AND_HOME", name: "House and Home"},
    {code: "LIBRARIES_AND_DEMO", name: "Libraries and Demo"},
    {code: "LIFESTYLE", name: "Lifestyle"},
    {code: "MAPS_AND_NAVIGATION", name: "Maps and Navigation"},
    {code: "MEDICAL", name: "Medical"},
    {code: "MUSIC_AND_AUDIO", name: "Music and Audio"},
    {code: "NEWS_AND_MAGAZINES", name: "News and Magazines"},
    {code: "PARENTING", name: "Parenting"},
    {code: "PERSONALIZATION", name: "Personalization"},
    {code: "PHOTOGRAPHY", name: "Photography"},
    {code: "PRODUCTIVITY", name: "Productivity"},
    {code: "SHOPPING", name: "Shopping"},
    {code: "SOCIAL", name: "Social"},
    {code: "SPORTS", name: "Sports"},
    {code: "TOOLS", name: "Tools"},
    {code: "TRAVEL_AND_LOCAL", name: "Travel and Local"},
    {code: "VIDEO_PLAYERS", name: "Video Players"},
    {code: "WATCH_FACE", name: "Watch Face"},
    {code: "WEATHER", name: "Weather"},
    {code: "GAME", name: "Games"},
    {code: "GAME_ACTION", name: "Action Games"},
    {code: "GAME_ADVENTURE", name: "Adventure Games"},
    {code: "GAME_ARCADE", name: "Arcade Games"},
    {code: "GAME_BOARD", name: "Board Games"},
    {code: "GAME_CARD", name: "Card Games"},
    {code: "GAME_CASINO", name: "Casino Games"},
    {code: "GAME_CASUAL", name: "Casual Games"},
    {code: "GAME_EDUCATIONAL", name: "Educational Games"},
    {code: "GAME_MUSIC", name: "Music Games"},
    {code: "GAME_PUZZLE", name: "Puzzle Games"},
    {code: "GAME_RACING", name: "Racing Games"},
    {code: "GAME_ROLE_PLAYING", name: "Role Playing Games"},
    {code: "GAME_SIMULATION", name: "Simulation Games"},
    {code: "GAME_SPORTS", name: "Sports Games"},
    {code: "GAME_STRATEGY", name: "Strategy Games"},
    {code: "GAME_TRIVIA", name: "Trivia Games"},
    {code: "GAME_WORD", name: "Word Games"},
    {code: "FAMILY", name: "Family"},
];


export const iosCollections = [
    {device: 'MAC', collections: [
            {code: 'topmacapps', name: 'Top Mac Apps'},
            {code: 'topfreemacapps', name: ' Top Free Mac Apps'},
            {code: 'topgrossingmacapps', name: 'Top Grossing Mac Apps'},
            {code: 'toppaidmacapps', name: 'Top Paid Mac Apps'}
        ]
    },
    {device: 'IOS', collections: [
            {code: 'newapplications', name: 'New iOS Apps'},
            {code: 'newfreeapplications', name: 'New Free iOS Apps'},
            {code: 'newpaidapplications', name: 'New Paid iOS Apps'},
            {code: 'topfreeapplications', name: 'Top Free iOS Apps'},
            {code: 'toppaidapplications', name: 'Top Paid iOS Apps'},
            {code: 'topgrossingapplications', name: 'Top Grossing iOS Apps'},
        ]
    },
    {device: 'IPAD', collections: [
            {code: 'topfreeipadapplications', name: 'Top Free iPad Apps'},
            {code: 'toppaidipadapplications', name: 'Top Paid iPad Apps'},
            {code: 'topgrossingipadapplications', name: 'Top Grossing iPad Apps'}
        ]
    }
];
  
export const iosCategories = [
    {code: '', name: "Category (Optional)", csvName: ''},
    {name: 'Books', code: 6018, csvName: 'BOOKS',},
    {name: 'Business', code: 6000, csvName: 'BUSINESS',},
    {name: 'Catalogs', code: 6022, csvName: 'CATALOGS',},
    {name: 'Education', code: 6017, csvName: 'EDUCATION',},
    {name: 'Entertainment', code: 6016, csvName: 'ENTERTAINMENT',},
    {name: 'Finance', code: 6015, csvName: 'FINANCE',},
    {name: 'Food and Drink', code: 6023, csvName: 'FOOD_AND_DRINK',},
    {name: 'Games', code: 6014, csvName: 'GAMES',},
    {name: 'Action Games', code: 7001, csvName: 'GAMES_ACTION',},
    {name: 'Adventure Games', code: 7002, csvName: 'GAMES_ADVENTURE',},
    {name: 'Arcade Games', code: 7003, csvName: 'GAMES_ARCADE',},
    {name: 'Board Games', code: 7004, csvName: 'GAMES_BOARD',},
    {name: 'Card Games', code: 7005, csvName: 'GAMES_CARD',},
    {name: 'Casino Games', code: 7006, csvName: 'GAMES_CASINO',},
    {name: 'Dice Games', code: 7007, csvName: 'GAMES_DICE',},
    {name: 'Educational Games', code: 7008, csvName: 'GAMES_EDUCATIONAL',},
    {name: 'Family Games', code: 7009, csvName: 'GAMES_FAMILY',},
    {name: 'Music Games', code: 7011, csvName: 'GAMES_MUSIC',},
    {name: 'Puzzle Games', code: 7012, csvName: 'GAMES_PUZZLE',},
    {name: 'Racing Games', code: 7013, csvName: 'GAMES_RACING',},
    {name: 'Role Playing Games', code: 7014, csvName: 'GAMES_ROLE_PLAYING',},
    {name: 'Simulation Games', code: 7015, csvName: 'GAMES_SIMULATION',},
    {name: 'Sports Games', code: 7016, csvName: 'GAMES_SPORTS',},
    {name: 'Strategy Games', code: 7017, csvName: 'GAMES_STRATEGY',},
    {name: 'Trivia Games', code: 7018, csvName: 'GAMES_TRIVIA',},
    {name: 'Word Games', code: 7019, csvName: 'GAMES_WORD',},
    {name: 'Health and Fitness', code: 6013, csvName: 'HEALTH_AND_FITNESS',},
    {name: 'Lifestyle', code: 6012, csvName: 'LIFESTYLE',},
    {name: 'Magazines and Newspapers', code: 6021, csvName: 'MAGAZINES_AND_NEWSPAPERS',},
    {name: 'Art Magazines', code: 13007, csvName: 'MAGAZINES_ARTS',},
    {name: 'Automotive Magazines', code: 13006, csvName: 'MAGAZINES_AUTOMOTIVE',},
    {name: 'Wedding Magazines', code: 13008, csvName: 'MAGAZINES_WEDDINGS',},
    {name: 'Business Magazines', code: 13009, csvName: 'MAGAZINES_BUSINESS',},
    {name: 'Children Magazines', code: 13010, csvName: 'MAGAZINES_CHILDREN',},
    {name: 'Computer Magazines', code: 13011, csvName: 'MAGAZINES_COMPUTER',},
    {name: 'Food Magazines', code: 13012, csvName: 'MAGAZINES_FOOD',},
    {name: 'Craft Magazines', code: 13013, csvName: 'MAGAZINES_CRAFTS',},
    {name: 'Electronics Magazines', code: 13014, csvName: 'MAGAZINES_ELECTRONICS',},
    {name: 'Entertainment Magazines', code: 13015, csvName: 'MAGAZINES_ENTERTAINMENT',},
    {name: 'Fashion Magazines', code: 13002, csvName: 'MAGAZINES_FASHION',},
    {name: 'Health Magazines', code: 13017, csvName: 'MAGAZINES_HEALTH',},
    {name: 'History Magazines', code: 13018, csvName: 'MAGAZINES_HISTORY',},
    {name: 'Home Magazines', code: 13003, csvName: 'MAGAZINES_HOME',},
    {name: 'Literary Magazines', code: 13019, csvName: 'MAGAZINES_LITERARY',},
    {name: 'Men Magazines', code: 13020, csvName: 'MAGAZINES_MEN',},
    {name: 'Movies and Music Magazines', code: 13021, csvName: 'MAGAZINES_MOVIES_AND_MUSIC',},
    {name: 'Politics Magazines', code: 13001, csvName: 'MAGAZINES_POLITICS',},
    {name: 'Outdoors Magazines', code: 13004, csvName: 'MAGAZINES_OUTDOORS',},
    {name: 'Family Magazines', code: 13023, csvName: 'MAGAZINES_FAMILY',},
    {name: 'Pet Magazines', code: 13024, csvName: 'MAGAZINES_PETS',},
    {name: 'Professional Magazines', code: 13025, csvName: 'MAGAZINES_PROFESSIONAL',},
    {name: 'Regional Magazines', code: 13026, csvName: 'MAGAZINES_REGIONAL',},
    {name: 'Science Magazines', code: 13027, csvName: 'MAGAZINES_SCIENCE',},
    {name: 'Sports Magazines', code: 13005, csvName: 'MAGAZINES_SPORTS',},
    {name: 'Teens Magazines', code: 13028, csvName: 'MAGAZINES_TEENS',},
    {name: 'Travel Magazines', code: 13029, csvName: 'MAGAZINES_TRAVEL',},
    {name: 'Women Magazines', code: 13030, csvName: 'MAGAZINES_WOMEN',},
    {name: 'Medical', code: 6020, csvName: 'MEDICAL',},
    {name: 'Music', code: 6011, csvName: 'MUSIC',},
    {name: 'Navigation', code: 6010, csvName: 'NAVIGATION',},
    {name: 'News', code: 6009,  csvName: 'NEWS',},
    {name: 'Photo and Video', code: 6008, csvName: 'PHOTO_AND_VIDEO',},
    {name: 'Productivity', code: 6007, csvName: 'PRODUCTIVITY',},
    {name: 'Reference', code: 6006, csvName: 'REFERENCE',},
    {name: 'Shopping', code: 6024, csvName: 'SHOPPING',},
    {name: 'Social Networking', code: 6005, csvName: 'SOCIAL_NETWORKING',},
    {name: 'Sports', code: 6004, csvName: 'SPORTS',},
    {name: 'Travel', code: 6003, csvName: 'TRAVEL',},
    {name: 'Utilities', code: 6002, csvName: 'UTILITIES',},
    {name: 'Weather', code: 6001, csvName: 'WEATHER',}
];

export const iosDevices = [
    {name: 'Mac', code: 'MAC'},
    {name: 'iOS', code: 'IOS'},
    {name: 'iPad', code: 'IPAD'},
]