import React from "react";


export const gplayCollections = [
    {code: "TOP_FREE", name: "Top Free"},
    {code: "TOP_PAID", name: "Top Paid"},
    {code: "GROSSING", name: "Top Grossing"},
]

export const gplayCategories = [
    {code: "", name: "Category (Optional)"},
    {code: "APPLICATION", name: "Application"},
    {code: "ANDROID_WEAR", name: "Android Wear"},
    {code: "ART_AND_DESIGN", name: "Art and Design"},
    {code: "AUTO_AND_VEHICLES", name: "Auto and Vehicle"},
    {code: "BEAUTY", name: "Beauty"},
    {code: "BOOKS_AND_REFERENCE", name: "Books and Reference"},
    {code: "BUSINESS", name: "Business"},
    {code: "COMICS", name: "Comics"},
    {code: "COMMUNICATION", name: "Communication"},
    {code: "DATING", name: "Dating"},
    {code: "EDUCATION", name: "Education"},
    {code: "ENTERTAINMENT", name: "Entertainment"},
    {code: "EVENTS", name: "Events"},
    {code: "FINANCE", name: "Finance"},
    {code: "FOOD_AND_DRINK", name: "Food and Drink"},
    {code: "HEALTH_AND_FITNESS", name: "Health and Fitness"},
    {code: "HOUSE_AND_HOME", name: "House and Home"},
    {code: "LIBRARIES_AND_DEMO", name: "Libraries and Demo"},
    {code: "LIFESTYLE", name: "Lifestyle"},
    {code: "MAPS_AND_NAVIGATION", name: "Maps and Navigation"},
    {code: "MEDICAL", name: "Medical"},
    {code: "MUSIC_AND_AUDIO", name: "Music and Audio"},
    {code: "NEWS_AND_MAGAZINES", name: "News and Magazines"},
    {code: "PARENTING", name: "Parenting"},
    {code: "PERSONALIZATION", name: "Personalization"},
    {code: "PHOTOGRAPHY", name: "Photography"},
    {code: "PRODUCTIVITY", name: "Productivity"},
    {code: "SHOPPING", name: "Shopping"},
    {code: "SOCIAL", name: "Social"},
    {code: "SPORTS", name: "Sports"},
    {code: "TOOLS", name: "Tools"},
    {code: "TRAVEL_AND_LOCAL", name: "Travel and Local"},
    {code: "VIDEO_PLAYERS", name: "Video Players"},
    {code: "WATCH_FACE", name: "Watch Face"},
    {code: "WEATHER", name: "Weather"},
    {code: "GAME", name: "Games"},
    {code: "GAME_ACTION", name: "Action Games"},
    {code: "GAME_ADVENTURE", name: "Adventure Games"},
    {code: "GAME_ARCADE", name: "Arcade Games"},
    {code: "GAME_BOARD", name: "Board Games"},
    {code: "GAME_CARD", name: "Card Games"},
    {code: "GAME_CASINO", name: "Casino Games"},
    {code: "GAME_CASUAL", name: "Casual Games"},
    {code: "GAME_EDUCATIONAL", name: "Educational Games"},
    {code: "GAME_MUSIC", name: "Music Games"},
    {code: "GAME_PUZZLE", name: "Puzzle Games"},
    {code: "GAME_RACING", name: "Racing Games"},
    {code: "GAME_ROLE_PLAYING", name: "Role Playing Games"},
    {code: "GAME_SIMULATION", name: "Simulation Games"},
    {code: "GAME_SPORTS", name: "Sports Games"},
    {code: "GAME_STRATEGY", name: "Strategy Games"},
    {code: "GAME_TRIVIA", name: "Trivia Games"},
    {code: "GAME_WORD", name: "Word Games"},
    {code: "FAMILY", name: "Family"},
];


export const iosCollections = [
    {device: 'MAC', collections: [
            {code: 'TOP_MAC', name: 'Top Mac Apps'},
            {code: 'TOP_FREE_MAC', name: ' Top Free Mac Apps'},
            {code: 'TOP_GROSSING_MAC', name: 'Top Grossing Mac Apps'},
            {code: 'TOP_PAID_MAC', name: 'Top Paid Mac Apps'}
        ]
    },
    {device: 'IOS', collections: [
            {code: 'NEW_IOS', name: 'New iOS Apps'},
            {code: 'NEW_FREE_IOS', name: 'New Free iOS Apps'},
            {code: 'NEW_PAID_IOS', name: 'New Paid iOS Apps'},
            {code: 'TOP_FREE_IOS', name: 'Top Free iOS Apps'},
            {code: 'TOP_PAID_IOS', name: 'Top Paid iOS Apps'},
            {code: 'TOP_GROSSING_IOS', name: 'Top Grossing iOS Apps'},
        ]
    },
    {device: 'IPAD', collections: [
            {code: 'TOP_FREE_IPAD', name: 'Top Free iPad Apps'},
            {code: 'TOP_PAID_IPAD', name: 'Top Paid iPad Apps'},
            {code: 'TOP_GROSSING_IPAD', name: 'Top Grossing iPad Apps'}
        ]
    }
];
  
export const iosCategories = [
    {code: "", name: "Category (Optional)"},
    {name: 'Books', code: 6018},
    {name: 'Business', code: 6000},
    {name: 'Catalogs', code: 6022},
    {name: 'Education', code: 6017},
    {name: 'Entertainment', code: 6016},
    {name: 'Finance', code: 6015},
    {name: 'Food and Drink', code: 6023},
    {name: 'Games', code: 6014},
    {name: 'Action Games', code: 7001},
    {name: 'Adventure Games', code: 7002},
    {name: 'Arcade Games', code: 7003},
    {name: 'Board Games', code: 7004},
    {name: 'Card Games', code: 7005},
    {name: 'Casino Games', code: 7006},
    {name: 'Dice Games', code: 7007},
    {name: 'Educational Games', code: 7008},
    {name: 'Family Games', code: 7009},
    {name: 'Music Games', code: 7011},
    {name: 'Puzzle Games', code: 7012},
    {name: 'Racing Games', code: 7013},
    {name: 'Role Playing Games', code: 7014},
    {name: 'Simulation Games', code: 7015},
    {name: 'Sports Games', code: 7016},
    {name: 'Strategy Games', code: 7017},
    {name: 'Trivia Games', code: 7018},
    {name: 'Word Games', code: 7019},
    {name: 'Health and Fitness', code: 6013},
    {name: 'Lifestyle', code: 6012},
    {name: 'Magazines and Newspapers', code: 6021},
    {name: 'Art Magazines', code: 13007},
    {name: 'Automotive Magazines', code: 13006},
    {name: 'Wedding Magazines', code: 13008},
    {name: 'Business Magazines', code: 13009},
    {name: 'Children Magazines', code: 13010},
    {name: 'Computer Magazines', code: 13011},
    {name: 'Food Magazines', code: 13012},
    {name: 'Craft Magazines', code: 13013},
    {name: 'Electronics Magazines', code: 13014},
    {name: 'Entertainment Magazines', code: 13015},
    {name: 'Fashion Magazines', code: 13002},
    {name: 'Health Magazines', code: 13017},
    {name: 'History Magazines', code: 13018},
    {name: 'Home Magazines', code: 13003},
    {name: 'Literary Magazines', code: 13019},
    {name: 'Men Magazines', code: 13020},
    {name: 'Movies and Music Magazines', code: 13021},
    {name: 'Politics Magazines', code: 13001},
    {name: 'Outdoors Magazines', code: 13004},
    {name: 'Family Magazines', code: 13023},
    {name: 'Pet Magazines', code: 13024},
    {name: 'Professional Magazines', code: 13025},
    {name: 'Regional Magazines', code: 13026},
    {name: 'Science Magazines', code: 13027},
    {name: 'Sports Magazines', code: 13005},
    {name: 'Teens Magazines', code: 13028},
    {name: 'Travel Magazines', code: 13029},
    {name: 'Women Magazines', code: 13030},
    {name: 'Medical', code: 6020},
    {name: 'Music', code: 6011},
    {name: 'Navigation', code: 6010},
    {name: 'News', code: 6009},
    {name: 'Photo and Video', code: 6008},
    {name: 'Productivity', code: 6007},
    {name: 'Reference', code: 6006},
    {name: 'Shopping', code: 6024},
    {name: 'Social Networking', code: 6005},
    {name: 'Sports', code: 6004},
    {name: 'Travel', code: 6003},
    {name: 'Utilities', code: 6002},
    {name: 'Weather', code: 6001}
];

export const iosDevices = [
    {name: 'Mac', code: 'MAC'},
    {name: 'iOS', code: 'IOS'},
    {name: 'iPad', code: 'IPAD'},
]