import React from "react";


export const gplayCollections = [
    {code: "", name: "Category (Optional)"},
    {code: "TOP_FREE", name: "Top Free"},
    {code: "TOP_PAID", name: "Top Paid"},
    {code: "GROSSING", name: "Top Grossing"},
]

export const gplayCategories = [
 {code: "", name: "Category (Optional)"},
 {code: "APPLICATION", name: "Application"},
 {code: "ANDROID_WEAR", name: "Android Wear"},
 {code: "ART_AND_DESIGN", name: "Art and Design"},
 {code: "AUTO_AND_VEHICLES", name: "Auto and Vehicle"},
 {code: "BEAUTY", name: "Beauty"},
 {code: "BOOKS_AND_REFERENCE", name: "Books and Reference"},
 {code: "BUSINESS", name: "Business"},
 {code: "COMICS", name: "Comics"},
 {code: "COMMUNICATION", name: "Communication"},
 {code: "DATING", name: "Dating"},
 {code: "EDUCATION", name: "Education"},
 {code: "ENTERTAINMENT", name: "Entertainment"},
 {code: "EVENTS", name: "Events"},
 {code: "FINANCE", name: "Finance"},
 {code: "FOOD_AND_DRINK", name: "Food and Drink"},
 {code: "HEALTH_AND_FITNESS", name: "Health and Fitness"},
 {code: "HOUSE_AND_HOME", name: "House and Home"},
 {code: "LIBRARIES_AND_DEMO", name: "Libraries and Demo"},
 {code: "LIFESTYLE", name: "Lifestyle"},
 {code: "MAPS_AND_NAVIGATION", name: "Maps and Navigation"},
 {code: "MEDICAL", name: "Medical"},
 {code: "MUSIC_AND_AUDIO", name: "Music and Audio"},
 {code: "NEWS_AND_MAGAZINES", name: "News and Magazines"},
 {code: "PARENTING", name: "Parenting"},
 {code: "PERSONALIZATION", name: "Personalization"},
 {code: "PHOTOGRAPHY", name: "Photography"},
 {code: "PRODUCTIVITY", name: "Productivity"},
 {code: "SHOPPING", name: "Shopping"},
 {code: "SOCIAL", name: "Social"},
 {code: "SPORTS", name: "Sports"},
 {code: "TOOLS", name: "Tools"},
 {code: "TRAVEL_AND_LOCAL", name: "Travel and Local"},
 {code: "VIDEO_PLAYERS", name: "Video Players"},
 {code: "WATCH_FACE", name: "Watch Face"},
 {code: "WEATHER", name: "Weather"},
 {code: "GAME", name: "Games"},
 {code: "GAME_ACTION", name: "Action Games"},
 {code: "GAME_ADVENTURE", name: "Adventure Games"},
 {code: "GAME_ARCADE", name: "Arcade Games"},
 {code: "GAME_BOARD", name: "Board Games"},
 {code: "GAME_CARD", name: "Card Games"},
 {code: "GAME_CASINO", name: "Casino Games"},
 {code: "GAME_CASUAL", name: "Casual Games"},
 {code: "GAME_EDUCATIONAL", name: "Educational Games"},
 {code: "GAME_MUSIC", name: "Music Games"},
 {code: "GAME_PUZZLE", name: "Puzzle Games"},
 {code: "GAME_RACING", name: "Racing Games"},
 {code: "GAME_ROLE_PLAYING", name: "Role Playing Games"},
 {code: "GAME_SIMULATION", name: "Simulation Games"},
 {code: "GAME_SPORTS", name: "Sports Games"},
 {code: "GAME_STRATEGY", name: "Strategy Games"},
 {code: "GAME_TRIVIA", name: "Trivia Games"},
 {code: "GAME_WORD", name: "Word Games"},
 {code: "FAMILY", name: "Family"},
];